
[server]
port = 8502
address = "0.0.0.0"
headless = true
enableCORS = false
enableWebsocketCompression = false
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
